// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2fhMaZJzJIUnbKqRx6ppfcSiOpz70XM',
    appId: '1:261120333223:web:f17ff72b9e13fbdedd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    authDomain: 'thefire-world.firebaseapp.com',
    storageBucket: 'thefire-world.appspot.com',
    measurementId: 'G-LHWKD9FVJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDmu2ANiJ4Ln2kFXr0bPFipuZ922sj64',
    appId: '1:261120333223:android:0d02fe19a2faac1bdd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    storageBucket: 'thefire-world.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUBAS4MIwSzpCTOdfS3UHGbHaKAQ8HFU',
    appId: '1:261120333223:ios:9d984f7f8f705413dd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    storageBucket: 'thefire-world.appspot.com',
    androidClientId: '261120333223-7kkc7k6irqvtke7c6finhj61begngu7n.apps.googleusercontent.com',
    iosClientId: '261120333223-p2cu0i067mrinh1gch063eebccecnlnn.apps.googleusercontent.com',
    iosBundleId: 'wtf.iamsihu.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUBAS4MIwSzpCTOdfS3UHGbHaKAQ8HFU',
    appId: '1:261120333223:ios:9d984f7f8f705413dd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    storageBucket: 'thefire-world.appspot.com',
    androidClientId: '261120333223-7kkc7k6irqvtke7c6finhj61begngu7n.apps.googleusercontent.com',
    iosClientId: '261120333223-p2cu0i067mrinh1gch063eebccecnlnn.apps.googleusercontent.com',
    iosBundleId: 'wtf.iamsihu.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA2fhMaZJzJIUnbKqRx6ppfcSiOpz70XM',
    appId: '1:261120333223:web:4d88cd161a3765b7dd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    authDomain: 'thefire-world.firebaseapp.com',
    storageBucket: 'thefire-world.appspot.com',
    measurementId: 'G-QZ4FBJENW1',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBA2fhMaZJzJIUnbKqRx6ppfcSiOpz70XM',
    appId: '1:261120333223:web:13cab746a389d179dd9282',
    messagingSenderId: '261120333223',
    projectId: 'thefire-world',
    authDomain: 'thefire-world.firebaseapp.com',
    storageBucket: 'thefire-world.appspot.com',
    measurementId: 'G-FWCRYWPGFY',
  );
}
